# Generated by Django 2.0.6 on 2020-09-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelTable(
            name='school',
            table='zhf_school',
        ),
    ]
