# Generated by Django 2.0.6 on 2020-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api3', '0003_auto_20200916_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
